# [[main]]
# url = "/workers"
# name = "作品"
# weight = 3

[[main]]
url = "/posts"
name = "文章"
weight = 4
[[main]]
url = "https://github.com/greenhat616"
name = "Github"
weight = 1
[[main]]
url = "/friends"
name = "朋友们"
weight = 2
[[main]]
url = "/index.xml"
name = "RSS"
weight = 5