baseURL = 'https://i.a632079.me/'
languageCode = 'zh-cn'
title = '藤之青'
copyright = "2022 a632079"
theme = ['diary']

timeZone = 'Asia/Shanghai'
DefaultContentLanguage = 'zh'
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true

[param]
enableVue = true

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "perldoc"
tabWidth = 4
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
